### ISSUE TITLE
Auto-merge fails when PR is created as a draft

### ISSUE THREAD

**Issue by zapteryx** [reitermarkus/automerge#1525]
https://github.com/ZPTXDev/Quaver/pull/427
https://github.com/ZPTXDev/Quaver/runs/7704902859?check_suite_focus=true
When a PR is created as a draft, auto-merge is already disabled (and I assume it's not possible to modify the state of auto-merge externally when in this state). The run fails with an error.

**Comment by zapteryx** [comment]
Another one when auto-merge is run on a draft PR:
https://github.com/ZPTXDev/Quaver/runs/7706134245?check_suite_focus=true

**Comment by reitermarkus** [comment]
Thanks, @zapteryx. It seems like there was a change at some point that automatically disables auto-merge for closed and draft PRs.

**Comment by reitermarkus** [comment]
Fixed in 2.1.2.
