### ISSUE TITLE
Problem with gpg signatures and rebase merges

### ISSUE THREAD

**Issue by thirionlogan** [reitermarkus/automerge#160]
FYI If you require signed commits on a protected branch that is being rebased and merged to, you will receive this error message: `Failed to merge pull request 45 (0 tries left): Base branch requires signed commits. Rebase merges cannot be automatically signed by GitHub`. According to [this](https://github.com/github/hub/issues/1241) issue, this is something that has been in the works for a while. I know this isn't something this project can fix, although I think it is important to know and might merit some warning in the documentation.

Maybe you can do some sort of workaround with tokens in the same way that [this action](https://github.com/Label305/AutoRebase) does

**Comment by reitermarkus** [comment]
> `Rebase merges cannot be automatically signed by GitHub.`

I assume the same happens when manually using the “Rebase and merge” button, in which case I don't think this needs to be added to the documentation if it already affects manual merging.

> Maybe you can do some sort of workaround with tokens in the same way that [this action](https://github.com/Label305/AutoRebase) does

This action doesn't seem to do anything to specifically handle signed commits?
