### ISSUE TITLE
Code climate checks are not detected

### ISSUE THREAD

**Issue by timon** [reitermarkus/automerge#183]
Hi Markus.

We recently added Code Climate to our repository and added a required check for `codeclimate` to succeed before our pull request gets merged. This broke the merge automation for us.

Turns out, code climate checks are not reported as a check run, but as a `Commit Status` ([Github reference](https://docs.github.com/en/rest/reference/repos#statuses)).

Required status checks detection should be updated to consider commit statuses as well.

*P.S. I'm adding this mostly for documentation, I think I would create a PR to address it next week. But if you'd like to do this yourself feel free to go ahead*

**Comment by reitermarkus** [comment]
Closed by https://github.com/reitermarkus/automerge/pull/190.
