### ISSUE TITLE
Not working anymore with ES 3.8

### ISSUE THREAD

**Issue by javimoya** [reitermarkus/automerge#2678]
<img width="793" alt="image" src="https://user-images.githubusercontent.com/371882/226418804-5eb1317f-859e-46fe-8e42-5657db3b6615.png">

https://docs.github.com/en/graphql/reference/input-objects#enablepullrequestautomergeinput
https://docs.github.com/en/enterprise-server@3.8/graphql/reference/input-objects#enablepullrequestautomergeinput

https://github.com/reitermarkus/automerge/blob/a0940449fc39725c7b88b4d859dfd6886478fac5/src/automerge-action.ts#L65

The input parameter expectedHeadOid is not part of ES 3.8

Thanks

**Comment by reitermarkus** [comment]
Have you contacted GitHub about this?

Is there a way to detect whether the action is running in ES 3.8?

**Comment by javimoya** [comment]
1) no. 
funny thing is that until 3.7 was working... but that expectedHeadOid  field was already not expected at 3.7 neither
https://docs.github.com/en/enterprise-server@3.7/graphql/reference/input-objects#enablepullrequestautomergeinput
2) Yes
  const response = await octokit.enterpriseAdmin.getGithubEnterprise();
  return response.data.enterprise.version;

Thanks

**Comment by javimoya** [comment]
oh... but you need a token with very high permissions to get those admin data. 😞  so it's not convenience...

maybe, instead (as a workaround), you can add an input parameter to indicate that?

**Comment by reitermarkus** [comment]
> funny thing is that until 3.7 was working

Passing `expectedHeadOid` was only added recently in this action, you were probably using an older version of this action with ES 3.7.

> no.

Please contact GitHub first to check with them whether this is intended or if the missing `expectedHeadOid` is a bug.

Maybe they can also provide a better way to get the ES version without admin privileges.
