### ISSUE TITLE
This action does not support the 'pull_request' event.

### ISSUE THREAD

**Issue by vsem-cinch** [reitermarkus/automerge#382]
Greetings. I am getting the following error;
"This action does not support the 'pull_request' event."

I am using the latest version.

Thanks

**Comment by reitermarkus** [comment]
Only the `pull_request_target` event is supported since you need access to secrets.

**Comment by vsem-cinch** [comment]
Actually, I figured it out. I created to have two separate GitHub Actions yaml files one for the pr.yml and another for the merge.yml  with:
`on:
  pull_request_review:
    types:
      - submitted`
and it worked.
Thanks

**Comment by vsem-cinch** [comment]
Next question: is there an input to close the PR after the merge?
Thanks

**Comment by reitermarkus** [comment]
If a PR is merged, it is also closed.

**Comment by vsem-cinch** [comment]
Okay thanks for some reason it's not doing that.
