### ISSUE TITLE
Fails when required checks/branch protection is created via ruleset

### ISSUE THREAD

**Issue by joshuasimon-taulia** [reitermarkus/automerge#3918]
Hi. The automerge action doesn't seem to be aware of branch required status checks created via enterprise [rulesets](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/available-rules-for-rulesets#require-status-checks-to-pass-before-merging). I have an example PR that's erroring out on

```
Evaluating mergeability for pull request 31:
Base branch 'main' of pull request 31 is not sufficiently protected.
Error: Resource not accessible by integration
```
but there are multiple required checks on the branch created via ruleset
![Screenshot 2024-01-25 at 5 24 44 PM](https://github.com/reitermarkus/automerge/assets/20404891/5b6f1c8f-6f16-4bbf-906b-0abd195610d0)

the strange thing is i fiddled with the gh cli as well and it shows the required checks as expected
```
gh pr checks --required 32
✓  pr/pullrequest / helm-build / helm-build (pull_request)
```

any idea if there's a simple fix i can apply to the [requiredStatusChecksForBranch](https://github.com/reitermarkus/automerge/blob/16240a2e5d9326c1b24f37f52e0bd76e7edeb847/src/helpers.ts#L67-L70) helper to get this to work as expected?

**Comment by reitermarkus** [comment]
@joshuasimon-taulia, not sure. I'd suggest you check the API output (https://docs.github.com/de/enterprise-server@3.12/rest/branches/branches?apiVersion=2022-11-28#get-a-branch) for the branch. There seems to be a `checks` field now in addition to `contexts`.

**Comment by reitermarkus** [comment]
I changed the check to use the `checks` field in https://github.com/reitermarkus/automerge/commit/80a3028214749c9dc93e3ff8d07d368c684220d5.

You can try `reitermarkus/automerge@main` to test it.

**Comment by joshuasimon-taulia** [comment]
i tried updating to https://github.com/reitermarkus/automerge/commit/80a3028214749c9dc93e3ff8d07d368c684220d5

```
Run reitermarkus/automerge@80a3028214749c9dc93e3ff8d07d368c684220d5
Evaluating mergeability for pull request 36:
Base branch 'main' of pull request 36 is not sufficiently protected.
Error: Resource not accessible by integration - https://docs.github.com/rest/users/users#get-the-authenticated-user
```
<img width="814" alt="Screenshot 2024-02-20 at 10 44 33 AM" src="https://github.com/reitermarkus/automerge/assets/20404891/cea85008-f22d-4acc-9e6b-a8cdd10fedb9">

here is the output of `gh pr checks --required 36`
```
Some checks were not successful
0 cancelled, 1 failing, 3 successful, 0 skipped, and 0 pending checks

   NAME                                      DESCRIPTION  ELAPSED  URL
X  pr/pullrequest / semantic-pr / Valida...               6s       https://github.com/orgzzz...
✓  pr/pullrequest / container-build (pul...               3m20s    https://github.com/orgzzz...
✓  pr/pullrequest / helm-build / helm-bu...               43s      https://github.com/orgzzz...
✓  pr/pullrequest / preview / preview (p...               29s      https://github.com/orgzzz...
```

maybe `(branch.protected === true && branch.protection.enabled === true)` needs to be adjusted to be ruleset aware

**Comment by reitermarkus** [comment]
@joshuasimon-taulia can you check if it is working now? I'll release a new version once confirmed working.

**Comment by joshuasimon-taulia** [comment]
```
Evaluating mergeability for pull request 36:
Base branch 'main' of pull request 36 is not sufficiently protected.
```

i believe https://github.com/reitermarkus/automerge/pull/4031/files#diff-4e0e66b64752cd230eb5f974fc26d665a896ab655d51b75bebf2bf67e1490ab5R182 accidentally reversed the logic so that auto merge is enabled on only branches **without** required checks 

fixed and working for me in https://github.com/reitermarkus/automerge/pull/4032
